### ISSUE TITLE
CloudFormation loader fails with !GetAtt

### ISSUE THREAD

**Issue by martin-macak** [martin-macak/aws-sam-testing#1]
## Steps to reproduce

Try to load the following template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API SAM Template
  
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.12

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Hello World function
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

## Current behaviour

```
loader = <aws_sam_testing.cfn.CloudFormationLoader object at 0x11421ee40>
node = ScalarNode(tag='!GetAtt', value='HelloWorldFunction.Arn')

    def construct_get_att(loader: yaml.Loader, node: yaml.Node) -> GetAttTag:
        """Construct !GetAtt tag."""
        if not isinstance(node, yaml.SequenceNode):
>           raise yaml.constructor.ConstructorError(
                None,
                None,
                "expected a sequence node, but found %s" % get_node_type_name(node),
                node.start_mark,
            )
E           yaml.constructor.ConstructorError: expected a sequence node, but found scalar
E             in "<unicode string>", line 40, column 12:
E                   Value: !GetAtt HelloWorldFunction.Arn
E                          ^

aws_sam_testing/cfn.py:135: ConstructorError
```

## Expected behaviour

The template is properly loaded with CloudFormation tags

## Root cause

The GetAtt node is not correctly implemented. The `!GetAtt` supports dot notation and array as well as defined at https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/intrinsic-function-reference-getatt.html.

Here's the example:

```
Fn::GetAtt: [ logicalNameOfResource, attributeName ]
```
equals to
```
!GetAtt logicalNameOfResource.attributeName
```
